# Generated by Django 4.0.3 on 2022-04-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'funcionario', 'verbose_name_plural': 'funcionarios'},
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
