# Generated by Django 4.0.3 on 2022-04-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='desconto',
            field=models.IntegerField(help_text='Desconto até 10%\n', max_length=2, null=True),
        ),
    ]
