# Generated by Django 4.0.3 on 2022-04-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_atendimento_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='desconto',
            field=models.IntegerField(default=0, help_text='Desconto até 10%\n', null=True),
        ),
    ]
