# Generated by Django 4.0.3 on 2022-04-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0008_atendimento_valor_alter_atendimento_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='servico',
        ),
        migrations.AddField(
            model_name='servico',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_app.atendimento'),
        ),
    ]
