# Generated by Django 4.0.3 on 2022-04-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0012_alter_atendimento_valor_total_alter_servico_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='atendimento',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_app.servico'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
