# Generated by Django 4.0.3 on 2022-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0013_remove_servico_atendimento_atendimento_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
