# Generated by Django 4.0.3 on 2022-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0014_alter_atendimento_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
